### ISSUE TITLE
Scalability issue of detail view sub menu

### ISSUE THREAD

**Issue by lehnerchristian** [Caleydo/ordino#37]
Currently the sub menu is divided into two parts:
- internal detail views showing different plots / lineup
- external detail views that load external resources

The more detail views are created for a specific IDType the longer the list gets.

Find a different way of showing the different detail views (e.g. with an accordion showing the top-level types (internal & external) and after expanding a top-level type show the detail views. For this approach more top-level types may be needed, like LineUp detail views, external, scatterplots to make it more scalable)

**Comment by mstreit** [comment]
Let's start simple with the following improvements:
- Add vertical scrollbars
- Remove spacing between the buttons so that the style more compact - maybe similar to the view history:
![image](https://cloud.githubusercontent.com/assets/4129755/23987097/046fac60-0a28-11e7-9737-92780f3ad135.png)
- Try to reduce height of buttons where the label is a one-liner.

**Comment by chrilehner** [comment]
a draft is here:

![submenu](https://cloud.githubusercontent.com/assets/1711080/24103065/648b05f0-0d7e-11e7-8536-63045259b396.png)


the submenu is wider along with some other changes. more detail views fit into the sub menu without the need to scroll
also I added a scrollbar to only scroll the submenu without scrolling the whole viewport

I'll also add headers (e.g. "Internal Views" above the first and "External Views" or "External Links" above the second block)
@zichner , do you like the compact version of the submenu or do you prefer the other one?

**Comment by zichner** [comment]
As long as we do not have too many detail views, I would make the buttons a bit bigger than in the draft, so that they do not look too packed and are still easy to click.
The sub-division of detail views, including the headers is nice. However, I suggest slightly different groups (will open a new ticket for that).
