### ISSUE TITLE
Adding and removing the same view twice causes application to crash

### ISSUE THREAD

**Issue by oltionchampari** [Caleydo/ordino#402]
### Environment 

 * Release number or git hash: develop
 * Browser: chrome
 * Deployed / Local: deployed & local

### Steps to reproduce the bug

1. Open a dataset 
2. Jump to the next view
3. Select a row
4. Close view and open it again
5. Select a row again
6. Replace the currently open view

### Observed Behavior

The application crashes and the views are unresponsive

### Expected Behavior

User should be able to replace view

### Screenshot

![grafik](https://user-images.githubusercontent.com/51322092/171830250-70977a47-fbc7-4489-98b5-63757eb45771.gif)

![error](https://user-images.githubusercontent.com/51322092/171830280-6ad9b10f-712d-4aa9-ac98-d69818557bc3.png)

**Comment by thinkh** [comment]
I can reproduce this error in my tests. I could even shorten it by omitting the selection in the copy number ranking.

The interesting fact is that only replacing the view (i.e., without add + remove before) works, but with adding and removing it breaks. My assumption is that the `ref` of the ViewWrapper is created and looked up by a generated _static_ hash. Hence, the object ref is created when adding the first view and gets removed. Then, with the second opening CLUE tries to reuse the previous object ref. However, that ref is not available anymore.

https://github.com/Caleydo/ordino/blob/a665c47ec56563c190c05091ea394872854453a7/src/internal/ViewWrapper.ts#L120

I investigate this hypothesis and see if this is the cause.

**Comment by thinkh** [comment]
I extended the `generateHash()` function by a random hash, to see whether or not the object ref is reused.

```ts
function generateHash(desc: IPluginDesc, selection: ISelection) {
  // const s = `${selection.idtype ? selection.idtype.id : ''}r${selection.ids}`;
  const s = `${selection.idtype ? selection.idtype.id : ''}r${selection.ids}_${BaseUtils.randomId()}`;
  return `${desc.id}_${s}`;
}
```

It turns out that with the random hash replacing the view after add + remove is working successfully! So my initial assumption seems to be confirmed.

![ordino-replace-view](https://user-images.githubusercontent.com/5851088/173822284-a0720903-5a6f-41cc-aaa1-9745e17c608a.gif)

Diffing the provenance graphs from [before](https://github.com/Caleydo/ordino/files/8909099/clue_add-remove-replace-fail.json.txt) and [after](https://github.com/Caleydo/ordino/files/8909102/clue_add-remove-replace-fail%2Brandom-ref-id.json.txt) the change reveals that the object reference is _not_ reused and the inverse action was added to the graph (which was previously not possible, due to the error within the replace action).

### Screenshots

Added random id

![image](https://user-images.githubusercontent.com/5851088/173822762-ca825401-c97b-4f91-bc15-178df03f49b9.png)


Successfully added inverse action

![image](https://user-images.githubusercontent.com/5851088/173822845-ecf15ee6-2125-4d97-8a3e-cee0df8736f0.png)

Reused object ref with id `14` and new object ref with id `21`; below the inverse edges

![image](https://user-images.githubusercontent.com/5851088/173823100-20aa8c23-9852-4eab-8e83-44849e016a8e.png)

![image](https://user-images.githubusercontent.com/5851088/173823468-b8add52f-1a6a-463f-af2e-81cf078df15a.png)


### Exported provenance graphs

* [clue_replace-view-only.json.txt](https://github.com/Caleydo/ordino/files/8909083/clue_replace-view-only.json.txt) -> works
* [clue_replace-view-only+random-ref-id.json.txt](https://github.com/Caleydo/ordino/files/8909084/clue_replace-view-only%2Brandom-ref-id.json.txt) -> works
* [clue_add-remove-replace-fail.json.txt](https://github.com/Caleydo/ordino/files/8909099/clue_add-remove-replace-fail.json.txt) -> fails
* [clue_add-remove-replace+random-ref-id.json.txt](https://github.com/Caleydo/ordino/files/8909102/clue_add-remove-replace-fail%2Brandom-ref-id.json.txt) -> works

### Follow up questions

1. What (side) effects would the random id in the hash have?
2. Why is the object ref added in both cases with id `21` (see last diff screenshot), but not used in the case without the random id?
3. Can we turn off / change the find object ref in CLUE?

**Comment by thinkh** [comment]
> 2. Why is the object ref added in both cases with id `21` (see last diff screenshot), but not used in the case without the random id?

The lookup (and reusage) is done in [`ProvenanceGraph.findInArray()`](https://github.com/datavisyn/tdp_core/blob/887bf8bf5f3b6ea2d9c1a5433cc031abdc7a2122/src/clue/provenance/ProvenanceGraph.ts#L302-L313) and executed in [`initAction()`](https://github.com/datavisyn/tdp_core/blob/887bf8bf5f3b6ea2d9c1a5433cc031abdc7a2122/src/clue/provenance/ProvenanceGraph.ts#L201-L210).

![image](https://user-images.githubusercontent.com/5851088/173827170-64cfc7de-3f37-43d8-9b98-81dd9c50dc7d.png)

Without the random id the same object with id `14` is used from the `_objects` array.

> 3. Can we turn off / change the find object ref in CLUE?

Most likely not. Hence, adding a random id is probably the only solution and we must check the effects as mentioned in question 1.

**Comment by thinkh** [comment]
I check further how and when this bug could have been introduced and I couldn't find any recent change that could cause this error. The [`existingView` variable in the `replaceViewImpl` is used](https://github.com/Caleydo/ordino/blob/66ef6910676960c580f6105d9e05ccffb17724cc/src/cmds.ts#L69) and also [the `generate_hash()` function hasn't changed](https://github.com/Caleydo/ordino/blob/20632732a860b81256f9f2a73257c8f966c58a62/src/ViewWrapper.ts#L20-L23) (beside using template strings) since the beginning.

Interestingly, the [`ViewWrapper` in tdp_core](https://github.com/datavisyn/tdp_core/blob/887bf8bf5f3b6ea2d9c1a5433cc031abdc7a2122/src/wrapper/ViewWrapper.ts#L158) uses [the default hash with `${name}_${category}` ](https://github.com/datavisyn/tdp_core/blob/887bf8bf5f3b6ea2d9c1a5433cc031abdc7a2122/src/clue/provenance/ObjectNode.ts#L64) and [creates `this.ref` with `graph.findOrAddObject()`](https://github.com/datavisyn/tdp_core/blob/887bf8bf5f3b6ea2d9c1a5433cc031abdc7a2122/src/wrapper/ViewWrapper.ts#L158). 

I applied the `graph.findOrAddObject()` and the `generate_hash()` without the random id (so original state) to the Ordino ViewWrapper and this also seems to work!

![ordino-replace-view-findOrAddObject](https://user-images.githubusercontent.com/5851088/173868086-3022a511-5ec9-4476-a519-e62b14cb16f3.gif)


### Screenshots

The interesting point here is that no additional object ref `21` is created and the object ref `14` is reused successfully.

![image](https://user-images.githubusercontent.com/5851088/173863718-f2fdd839-167c-422f-961d-c1a11f4b800b.png)

All following node ids are decreased by one, due to the missing object ref `21`. The screenshot also shows that the replace action was successful by adding the inverse action.

![image](https://user-images.githubusercontent.com/5851088/173864746-ce4cc4ae-7377-46c8-a5ce-abbb7fe4e7a1.png)

![image](https://user-images.githubusercontent.com/5851088/173864460-af7951f6-fd4e-4b73-b2f2-10448b391dcd.png)


### Exported provenance graphs

* [clue_add-remove-replace-fail.json.txt](https://github.com/Caleydo/ordino/files/8909099/clue_add-remove-replace-fail.json.txt) (same as in the [comment above](https://github.com/Caleydo/ordino/issues/402#issuecomment-1156394553))
* [clue_ref-with-findOrAddObject.json.txt](https://github.com/Caleydo/ordino/files/8910927/clue_ref-with-findOrAddObject.json.txt) -> works

**Comment by thinkh** [comment]
I've tested the compatibility with existing provenance graphs, by [exporting a session](https://github.com/Caleydo/ordino/files/8912805/Temporary.Session.28.json.txt) from Ordino Daily (without the ref change) and imported it locally (with the ref change) again. Additionally I've tested the [Ordino Paper Teaser Figure](https://github.com/Caleydo/ordino/files/8912802/Clone.of.Ordino.Paper.Teaser.Figure.json.txt). In my tests all actions like add, remove, replace views work without problems. Also jumping to a specific state and the inverse actions work for me.

I also imported the previously broken [clue_add-remove-replace-fail.json.txt](https://github.com/Caleydo/ordino/files/8909099/clue_add-remove-replace-fail.json.txt) session and now Ordino continues and finishes the action to replace the view. The graph got extended by the previously missing inverse action. Users could continue that session now.
