### ISSUE TITLE
Test Ordino in MS Edge

### ISSUE THREAD

**Issue by lehnerchristian** [Caleydo/ordino#93]
check effort to use Ordino in Edge

**Comment by sgratzl** [comment]
check when we switch to the next lineup version

**Comment by thinkh** [comment]
I guess the switch is done, once the PR https://github.com/datavisyn/tdp_core/pull/47 is merged.

**Comment by sgratzl** [comment]
to be reevaluated after https://github.com/datavisyn/tdp_core/issues/108

**Comment by mstreit** [comment]
still valid?

**Comment by thinkh** [comment]
Should be solved soon by itself once the [Edge browser is based on Chromium](https://www.microsoftedgeinsider.com/en-us/).

**Comment by thinkh** [comment]
Quick test with Ordino v6.0.1 and Edge 44

Users get the prompt that Ordino might not work with Internet Explorer.

![grafik.png](https://images.zenhubusercontent.com/599562848f62dc7798c31c64/e52f3541-90d1-4d72-96ff-75725968c1c3)

If I close the dialog and continue, Ordino is working as I would expect. It just feels a bit slower than in Chrome-based browsers or Firefox.

![grafik.png](https://images.zenhubusercontent.com/599562848f62dc7798c31c64/0dd92cf0-ffde-4f4a-8b36-0439f97aa267)

![grafik.png](https://images.zenhubusercontent.com/599562848f62dc7798c31c64/0cf81c0a-ea08-4ef4-b7ce-05e62f5297e1)

![grafik.png](https://images.zenhubusercontent.com/599562848f62dc7798c31c64/760bf99a-239f-4d80-9a75-573b4a2ae09b)

I'm closing this issue, since major things are working and we show the warning message on startup.

A quick test in Edge 78 (based on Chromium) shows that Ordino is working the same as in Google Chrome.
