### ISSUE TITLE
improve welcome page (aka start menu)

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/ordino#96]
we are limiting the space in the welcome page more than we need. Especially with more species and entity types the space is limited. 

Instead of a popup dialog, a base concept as in taggle could be useful

**Comment by mstreit** [comment]
This issue needs to be done in order to get Ordino public ready for submission. 
Things that should be shown:
- Brief intro text
- Schematic figure describing basic three step process: (1) welcome page for defining entities, (2) ranking and filtering in LineUp, (3) detail views. We already have a sketch in the datavisyn presentations.
- BI, JKU and datavisyn logos
- Note that the software is for research use only (copy text from about dialog)
- What else?

**Comment by thinkh** [comment]
@sgratzl or @mstreit Is this done since we have the new welcome page showing the instructions?

**Comment by mstreit** [comment]
welcome page != intro page. At some point, we want to redesign the welcome popup - but not for the paper.

**Comment by thinkh** [comment]
Ok, so you mean the start menu (or home menu)... ;-)

We should discuss more details before we can implement this.

**Comment by keckelt** [comment]
When visiting Ordino for the first time, users should see an introduction as currently.
This intro should be a popup.
When closing the popup, a cookie is saved that prevents it from opening again (until ordino was not used for e.g. 2 weeks).

The current start menu/home menu popup should fill the entire space. presenting the sets, persisted sessions etc better.

When starting a session, the welcome page is moved to the left. In this way, the whole application uses the "from left to right" navigation.

Additionally, opening session in another tab should work.

**Comment by anita-steiner** [comment]
see also https://github.com/Caleydo/tdp_bi_bioinfodb/issues/866

**Comment by thinkh** [comment]
Discussion moved to https://github.com/Caleydo/tdp_bi_bioinfodb/issues/1096.
